### PR TITLE
Better embeds tbh

### PR DESCRIPTION
**Pull request by pieckenst**
Here we are

### CODE REVIEW

**Comment by JDJGInc** [comment]
You also don't change the original text much, and when you do, you **must** keep the integrity of the original message.

**Comment by pieckenst** [comment]
tbh feel free to edit

**Comment by JDJGInc** [comment]
I will only commit this when the embeds are good for me to use, I'll have Shadi edit it later lol.
@SilentSerenityy

**Comment by JDJGInc** [comment]
I am sorry about this, but requiring my code to be pep8 is no bueno. I will not merge this pr. 
However, I will manually change some changes I do like until my own release.

**Comment by JDJGInc** [comment]
This is all.

**Pull request closed without merging**
