### PR TITLE
Help command upgrade

### PR DESCRIPTION
**Pull request by thatrandomperson5**
#### Added: 
More help command embed things: like a Request by author field and a dynamic description to help stop people from doing `{p}help bot` or `{p}Bot` instead of `{p}help Bot`

Fix for [card 83944797](https://github.com/JDJGInc/JDBot/projects/1#card-83944797)

### CODE REVIEW

**Review by thatrandomperson5 — COMMENTED** [review]
No problems, double checked.

**Comment by JDJGInc** [comment]
This should not affect .gitignore.

**Comment by thatrandomperson5** [comment]
> This should not affect .gitignore.

I cannot find a way to undo commits, sry. It is the same as before, just extra commits.

**Review by JDJGInc — CHANGES_REQUESTED** [review]
.gitignore should not be affected, if it stays affected, this pull request will not be merged.

**Comment by JDJGInc** [comment]
Make sure to use black -l120 . for your code :)

**Comment by JDJGInc** [comment]
Juuzoq is aganist this (he really doesn't like black) and would rather waste a commit on formatting but please don't do that.

**Comment by JDJGInc** [comment]
Juuzoq is cool though and I thank him for his contributions :)
or at least he should know he's a useful person to have.

**Comment by thatrandomperson5** [comment]
> Make sure to use black -l120 . for your code :)

I have version 22.6.0

**Comment by JDJGInc** [comment]
> > Make sure to use black -l120 . for your code :)
> 
> I have version 22.6.0

You run black -l120 .

**Pull request closed without merging**
